syntax = "proto3";

package Custodex.Api;

option csharp_namespace = "Custodex.Api";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

message TenantContext {
  string store = 1;
  string tenant = 2;
}

message EntityRef {
  string type = 1;
  string id = 2;
}

message SubjectRef {
  string type = 1;
  string id = 2;
  string relation = 3;
}

message ConditionRef {
  string name = 1;
  google.protobuf.Struct parameters = 2;
}

message RequestContext {
  google.protobuf.Timestamp now = 1;
  SubjectRef subject = 2;
  google.protobuf.Struct attributes = 3;
  Consistency consistency = 4;
}

enum ConsistencyMode {
  CONSISTENCY_MODE_MINIMIZE_LATENCY = 0;
  CONSISTENCY_MODE_AT_LEAST_AS_FRESH = 1;
  CONSISTENCY_MODE_FULLY_CONSISTENT = 2;
}

message Consistency {
  ConsistencyMode mode = 1;
  string token = 2;
}

message ExplainNode {
  string description = 1;
  bool allowed = 2;
  repeated ExplainNode children = 3;
}
