<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Custodex</RootNamespace>
		<UserSecretsId>0131408b-2821-4635-b8be-29852b7b5a16</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\custodex_common.proto" GrpcServices="None" />
		<Protobuf Include="Protos\custodex_decision.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Custodex.Core\Custodex.Core.csproj" />
	  <ProjectReference Include="..\Custodex.ServiceDefaults\Custodex.ServiceDefaults.csproj" />
	  <ProjectReference Include="..\Custodex.Storage.Postgres\Custodex.Storage.Postgres.csproj" />
	</ItemGroup>

</Project>
