<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <ProjectReference Include="..\Relkit.Abstractions\Relkit.Abstractions.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Relkit</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <InternalsVisibleTo Include="Relkit.Core.Tests" />
	</ItemGroup>

</Project>
